-- ============================================================================
-- 02_RAW_TABLES.SQL — Raw tables for Mining ESG & Sustainability
-- ============================================================================
USE DATABASE MINING_ESG;
USE SCHEMA RAW;

CREATE OR REPLACE TABLE RAW.EMISSIONS_DATA (
  ID VARCHAR DEFAULT UUID_STRING(),
  DATA VARIANT,
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE RAW.WATER_MONITORING (
  ID VARCHAR DEFAULT UUID_STRING(),
  DATA VARIANT,
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE RAW.COMMUNITY_PROGRAMS (
  ID VARCHAR DEFAULT UUID_STRING(),
  DATA VARIANT,
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE RAW.SAFETY_INCIDENTS (
  ID VARCHAR DEFAULT UUID_STRING(),
  DATA VARIANT,
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE RAW.TAILINGS_MONITORING (
  ID VARCHAR DEFAULT UUID_STRING(),
  DATA VARIANT,
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE RAW.ESG_REPORTS (
  ID VARCHAR DEFAULT UUID_STRING(),
  DATA VARIANT,
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

