-- Generated from generator/demo_specs/aws-indonesia-mining-nickel-esg.json
-- Regenerate with: python3 generator/gen_repo_docs.py aws-indonesia-mining-nickel-esg
-- This is the schema that is actually deployed for ID_MINING_NICKEL_ESG.

-- Alerts fire on the bottom tail of ESG Score (Avg)
-- (lower is worse for this metric).
CREATE OR REPLACE DYNAMIC TABLE CURATED.PERFORMANCE_SUMMARY
  TARGET_LAG = '30 days' WAREHOUSE = TOURISM_WH
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS
WITH thresh AS (
  SELECT PERCENTILE_CONT(0.09) WITHIN GROUP (ORDER BY KPI_ESG_SCORE_AVG) AS T
  FROM RAW.WATER_MONITORING
)
SELECT
  e.ID AS ENTITY_ID,
  e.NAME AS ENTITY_NAME,
  e.REGION,
  e.CATEGORY,
  e.STATUS,
  COUNT(*) AS EVENT_COUNT,
  SUM(CASE WHEN f.KPI_ESG_SCORE_AVG <= (SELECT T FROM thresh) THEN 1 ELSE 0 END) AS ALERT_COUNT,
  ROUND(AVG(f.KPI_ESG_SCORE_AVG), 2) AS AVG_ESG_SCORE,
  ROUND(AVG(f.KPI_REHABILITATION_AREA), 2) AS AVG_REHABILITATION_AREA,
  ROUND(AVG(f.KPI_WATER_RECYCLED), 2) AS AVG_WATER_RECYCLED,
  ROUND(AVG(f.KPI_BIODIVERSITY_INDEX), 2) AS AVG_BIODIVERSITY_INDEX
FROM RAW.WATER_MONITORING f
JOIN RAW.ESG_REPORTS e ON e.ID = f.ENTITY_ID
CROSS JOIN thresh
GROUP BY e.ID, e.NAME, e.REGION, e.CATEGORY, e.STATUS;

CREATE OR REPLACE DYNAMIC TABLE CURATED.TREND_ANALYSIS
  TARGET_LAG = '30 days' WAREHOUSE = TOURISM_WH
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS
SELECT
  f.EVENT_DATE AS METRIC_DATE,
  COUNT(*) AS EVENT_COUNT,
  ROUND(AVG(f.KPI_ESG_SCORE_AVG), 2) AS AVG_ESG_SCORE,
  ROUND(AVG(f.KPI_REHABILITATION_AREA), 2) AS AVG_REHABILITATION_AREA,
  ROUND(AVG(f.KPI_WATER_RECYCLED), 2) AS AVG_WATER_RECYCLED,
  ROUND(AVG(f.KPI_BIODIVERSITY_INDEX), 2) AS AVG_BIODIVERSITY_INDEX
FROM RAW.WATER_MONITORING f
GROUP BY f.EVENT_DATE;

-- DISPLAY is rendered here so it is byte-identical to the card the app
-- was designed with (asserted by the round-trip check in kpi_parse.py).
CREATE OR REPLACE DYNAMIC TABLE CURATED.KPI_SUMMARY
  TARGET_LAG = '30 days' WAREHOUSE = TOURISM_WH
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS WITH ev AS (SELECT AVG(KPI_ESG_SCORE_AVG) AS KPI_ESG_SCORE_AVG, AVG(KPI_REHABILITATION_AREA) AS KPI_REHABILITATION_AREA, AVG(KPI_WATER_RECYCLED) AS KPI_WATER_RECYCLED, AVG(KPI_BIODIVERSITY_INDEX) AS KPI_BIODIVERSITY_INDEX FROM RAW.WATER_MONITORING),
     en AS (SELECT SUM(KPI_EMISSIONS_MTD) AS KPI_EMISSIONS_MTD, SUM(KPI_SITES_MONITORED) AS KPI_SITES_MONITORED FROM RAW.ESG_REPORTS)
  SELECT 1 AS SORT_ORDER, 'ESG Score (Avg)' AS TITLE, KPI_ESG_SCORE_AVG AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_ESG_SCORE_AVG)) AS DECIMAL(38,0))) || '/100' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 2 AS SORT_ORDER, 'Emissions (MTD)' AS TITLE, KPI_EMISSIONS_MTD AS VALUE_NUM, TO_VARCHAR(CAST(ROUND(((KPI_EMISSIONS_MTD) / 1000)) AS DECIMAL(38,0))) || 'K' || ' ' || 'tCO2e' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 3 AS SORT_ORDER, 'Rehabilitation Area' AS TITLE, KPI_REHABILITATION_AREA AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_REHABILITATION_AREA)) AS DECIMAL(38,0))) || ' ' || 'ha' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 4 AS SORT_ORDER, 'Sites Monitored' AS TITLE, KPI_SITES_MONITORED AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_SITES_MONITORED)) AS DECIMAL(38,0))) AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 5 AS SORT_ORDER, 'Water Recycled' AS TITLE, KPI_WATER_RECYCLED AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_WATER_RECYCLED)) AS DECIMAL(38,0))) || '%' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 6 AS SORT_ORDER, 'Biodiversity Index' AS TITLE, KPI_BIODIVERSITY_INDEX AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_BIODIVERSITY_INDEX), 2) AS DECIMAL(38,2))) AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en;

ALTER DYNAMIC TABLE CURATED.PERFORMANCE_SUMMARY SUSPEND;
ALTER DYNAMIC TABLE CURATED.TREND_ANALYSIS SUSPEND;
ALTER DYNAMIC TABLE CURATED.KPI_SUMMARY SUSPEND;
