-- ============================================================================
-- 06_ML_MODELS.SQL — ML Functions for Mining ESG & Sustainability
-- ============================================================================
USE DATABASE MINING_ESG;
USE SCHEMA ML;

-- ML.FORECAST: EMISSIONS_FORECAST
CREATE OR REPLACE SNOWFLAKE.ML.FORECAST ML.EMISSIONS_FORECAST(
  INPUT_DATA => SYSTEM$REFERENCE('TABLE', 'CURATED.EMISSIONS_DASHBOARD'),
  SERIES_COLNAME => 'SITE_ID',
  TIMESTAMP_COLNAME => 'DS',
  TARGET_COLNAME => 'Y'
  
);

CREATE OR REPLACE TABLE ML.EMISSIONS_FORECAST_RESULTS AS
SELECT * FROM TABLE(ML.EMISSIONS_FORECAST!FORECAST(FORECASTING_PERIODS => 14));

-- ML.ANOMALY_DETECTION: DISCHARGE_ANOMALY_MODEL
CREATE OR REPLACE SNOWFLAKE.ML.ANOMALY_DETECTION ML.DISCHARGE_ANOMALY_MODEL(
  INPUT_DATA => SYSTEM$REFERENCE('TABLE', 'CURATED.WATER_BALANCE'),
  SERIES_COLNAME => 'MONITORING_POINT',
  TIMESTAMP_COLNAME => 'DS',
  TARGET_COLNAME => 'Y',
  LABEL_COLNAME => ''
);

CREATE OR REPLACE TABLE ML.DISCHARGE_ANOMALY_MODEL_RESULTS AS
SELECT * FROM TABLE(ML.DISCHARGE_ANOMALY_MODEL!DETECT_ANOMALIES(INPUT_DATA => SYSTEM$REFERENCE('TABLE', 'CURATED.WATER_BALANCE'), SERIES_COLNAME => 'MONITORING_POINT', TIMESTAMP_COLNAME => 'DS', TARGET_COLNAME => 'Y'));

