-- ============================================================================
-- 99_RESET.SQL — Reset Mining ESG & Sustainability to clean demo state
-- ============================================================================
USE DATABASE MINING_ESG;

-- Suspend tasks during demo
ALTER TASK IF EXISTS APP.TASK_INGEST_MONITORING SUSPEND;
ALTER TASK IF EXISTS APP.TASK_DETECT_ANOMALIES SUSPEND;
ALTER TASK IF EXISTS APP.TASK_FORECAST_EMISSIONS SUSPEND;

-- Force refresh Dynamic Tables
ALTER DYNAMIC TABLE CURATED.EMISSIONS_DASHBOARD REFRESH;
ALTER DYNAMIC TABLE CURATED.WATER_BALANCE REFRESH;
ALTER DYNAMIC TABLE CURATED.SAFETY_METRICS REFRESH;
ALTER DYNAMIC TABLE CURATED.TAILINGS_RISK REFRESH;

-- Verify key demo numbers
-- SELECT COUNT(*) FROM MINING_ESG.RAW.EMISSIONS_DATA → 100000
-- SELECT COUNT(*) FROM MINING_ESG.RAW.WATER_MONITORING → 200000
-- SELECT COUNT(*) FROM MINING_ESG.RAW.TAILINGS_MONITORING → 50000

-- Resume tasks
ALTER TASK IF EXISTS APP.TASK_FORECAST_EMISSIONS RESUME;
ALTER TASK IF EXISTS APP.TASK_DETECT_ANOMALIES RESUME;
ALTER TASK IF EXISTS APP.TASK_INGEST_MONITORING RESUME;
